# Screen Size and others
WIDTH, HEIGHT = 1280, 720
PADDING = 60
ROWS, COLS = 9, 16
FPS = 60
X_OFFSET = ((WIDTH - PADDING * 2) // COLS)
Y_OFFSET = ((HEIGHT - PADDING * 2) // ROWS)

CELL_WIDTH = X_OFFSET + 1
CELL_HEIGHT = Y_OFFSET + 1

ENTITY_WIDTH = X_OFFSET - 10
ENTITY_HEIGHT = Y_OFFSET - 10

# Colours and aesthetics
BACKGROUNDCOLOUR = (255, 255, 255)
WALLSCOLOUR = (0, 0, 0)
PLAYERCOLOUR = (255, 0, 0)
BLACK = (10, 10, 80)
FONT = "dejavusans"


# Game related
MAX_ATTRIBUTES = 3